### PR TITLE
Add reference to the `XtraFinder` app

### PR DESCRIPTION
**Pull request by caioproiete**

### CODE REVIEW

**Comment by caioproiete** [comment]
Hey @nicolashery, any chance of merging this one?
Cheers!

**Comment by vassyz** [comment]
Unfortunately, XtraFinder doesn't work out of the box anymore on El Capitan. And I'm not sure the author is committed enough to create a workaround for OSX's new security "features".

**Comment by caioproiete** [comment]
Hey @vassyz, indeed... Doesn't work out of the box - although it's not hard to [disable SIP for Xtrafinder to work](http://lifehacker.com/how-to-fix-os-x-el-capitans-annoyances-1733836821) (as well as other stuff like Homebrew for example)

I think it's a great utility that (despite requiring the extra step) should be added to the list.

What do you think?

**Comment by nicolashery** [comment]
Hi @caioproiete, thank you for your contribution! It's true that the default Finder is very lacking. I've been using Path Finder so far, but I'm glad to learn there are free or less expensive alternatives like XtraFinder!

Before adding anything to this guide however, I like to test the installs myself. The fact that you have to "hack" your OS is a little disconcerting. I'm running Yosemite, but I'll give it a try when I upgrade.

**Comment by caioproiete** [comment]
Hi @nicolashery, OK no problem.

To be fair, though when I opened the pull-request almost 6 months ago, no hack was needed! :smiley:

**Comment by vassyz** [comment]
@caioproiete This pull request is not going to be merged. Do you mind closing it?

**Comment by nicolashery** [comment]
XtraFinder seemed to be an interesting app. However, in the interest of keeping this guide short and simple, I only include a selection of apps I commonly use. I even removed the reference to Pathfinder which I don't really use anymore.

**Pull request closed without merging**
